version: '3.3'
services:
  app:
    build: ./app
    expose:
     - "26500"
    restart: on-failure:3
  nginx:
    image: nginx:alpine
    depends_on:
     - app
    volumes:
     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
     - 80:80
